In [25]:
import pandas as pd
from kiwipiepy import Kiwi

In [378]:
# df = pd.read_csv('../NEWS_NLP/Keword_cluster.csv')
df_origin = pd.read_csv('../Final_fire_news_4.csv')
# df = df_origin[['_id', 'send_timestamp','YNewsML.NewsContent.Title', 'YNewsML.NewsContent.Body','Summarization', 'key+jaccard']]

In [371]:
# df['send_timestamp'] = pd.to_datetime(df['send_timestamp'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11057 entries, 0 to 11056
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   _id                        11057 non-null  object
 1   send_timestamp             11057 non-null  object
 2   YNewsML.NewsContent.Title  11057 non-null  object
 3   YNewsML.NewsContent.Body   11057 non-null  object
 4   Summarization              11057 non-null  object
 5   key+jaccard                10594 non-null  object
dtypes: object(6)
memory usage: 518.4+ KB

In [491]:
df_issue = df['key+jaccard'].value_counts().to_frame().reset_index()
issue_1 = df_issue[df_issue['key+jaccard'] > 5].iloc[:,:]
issue_1

        index  key+jaccard
0        none         7212
1     이태원압사참사         1129
2          화재          352
3       힌남노태풍          296
4          태풍          235
5          지진          217
6         핼러윈          138
7         풍수해          107
8       폭우산사태           87
9        학동참사           77
10     태풍난마돌이           56
11         소방           50
12         산불           32
13   재난안전대응훈련           29
14         항공           25
15        4.9           25
16         10           23
17     을지태극연습           22
18     화정아이파크           20
19       수능시험           18
20       정기국회           18
21    세월호침몰사고           16
22       대한민국           14
23        월드컵           13
24         축제           10
25         테러           10
26  중앙지방정책협의회           10
27     안전문화포럼            7
28   소방기술경연대회            7
29   봉화광산매몰사고            7
30         양양            7
31      코로나19            6
32   10·29 참사            6

In [294]:
a = df[df['YNewsML.NewsContent.Body'].str.contains('SPC')]
table6 = pd.concat([table6,a])
table6 = table6[table6['send_timestamp'] >= '2022-10-21'].sort_values('send_timestamp')
table6 = table6.drop_duplicates()
table6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 4788 to 30
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   _id                        100 non-null    object
 1   send_timestamp             100 non-null    object
 2   YNewsML.NewsContent.Title  100 non-null    object
 3   YNewsML.NewsContent.Body   100 non-null    object
 4   Summarization              100 non-null    object
 5   key+jaccard                98 non-null     object
dtypes: object(6)
memory usage: 5.5+ KB

.

.

In [489]:
pick = df[(df['YNewsML.NewsContent.Title'].str.contains('종합5보'))]

kiwi = Kiwi()
b = pd.DataFrame()
for i in pick['YNewsML.NewsContent.Title']:
    a = []
    c = ''
    for result, score in kiwi.analyze(i, top_n=1):
        for j in range(len(result)):
            if result[j][1] == 'NNG':
                c += result[j][0] + ', '
    a.append(c)
    b = pd.concat([b,pd.DataFrame([a])],axis=0)
    
pick.head(2)

,_id,send_timestamp,YNewsML.NewsContent.Title,YNewsML.NewsContent.Body,Summarization,key+jaccard
4308,AKR20221029047958004,2022-10-30T07:17:38,이태원 '핼러윈 인파'에 149명 압사 참사…부상 76명(종합5보),"이태원 '핼러윈 인파'에 149명 압사 참사…부상 76명(종합5보)\n중상 19명,...",['소방당국은 이날 벌어진 사고로 30일 오전 6시 현재 149명이 숨지고 76명이...,핼러윈

In [486]:
b_li = b[0].tolist()
spell_list = []
for i in b_li:
    spell = []
    text = i.split(', ')
    for j in text:
        if (len(j) > 1) & (j != '종합') & (j != '사망') & (j != '부상')& (j != '장관')& (j != '현장') :
            spell.append(j)
    spell_list.append(spell)
spell_list[:2]

[['핼러윈', '인파', '압사', '참사']]

In [360]:
from itertools import combinations
aa = list(combinations(['종로','르메이에르','빌딩'][:4],2))
# aa = list(combinations(spell_list[0][:4],2))
aa

[('종로', '르메이에르'), ('종로', '빌딩'), ('르메이에르', '빌딩')]

In [361]:
# 검색
df_frame = pd.DataFrame()
for i in aa: 
    cond1 = df['YNewsML.NewsContent.Body'].str.contains(i[0])
    cond2 = df['YNewsML.NewsContent.Body'].str.contains(i[1])
    ddff = df[cond1&cond2]
    df_frame = pd.concat([df_frame, ddff])
    
table = df_frame.drop_duplicates().sort_values('send_timestamp')
table

,_id,send_timestamp,YNewsML.NewsContent.Title,YNewsML.NewsContent.Body,Summarization,key+jaccard
10303,AKR20220701074500004,2022-07-01T11:26:40,종로 르메이에르 빌딩 흔들림 신고…원인 조사 중,종로 르메이에르 빌딩 흔들림 신고…원인 조사 중\n\r\n<YNAOBJECT id=...,['1일 오전 10시 25분께 서울 종로구 르메이에르 빌딩이 흔들렸다는 신고가 들어...,none
10295,AKR20220701074551004,2022-07-01T12:05:09,종로 르메이에르 빌딩 흔들림으로 대피…출입 막고 원인조사(종합),"종로 르메이에르 빌딩 흔들림으로 대피…출입 막고 원인조사(종합)\n""5분간 흔들림 ...",['1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 흔들렸다는 신고가 들어와 소방...,none
10274,AKR20220701074552004,2022-07-01T14:50:21,종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합2보),종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합2보)\n옥상 냉각타워 파손...,['1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파...,none
10269,AKR20220701074553004,2022-07-01T15:56:12,종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합3보),종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합3보)\n옥상 냉각타워 파손...,['1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파...,none
10266,PYH20220701172200004,2022-07-01T16:35:00,종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피,종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피\r\n (서울=연합뉴스)...,['종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피 1일 오전 서울 종로구 르...,none
10262,AKR20220701140100704,2022-07-01T17:36:17,"[영상] ""빌딩이 흔들려요""…1천명 종로로 뛰어나온 공포의 4시간","[영상] ""빌딩이 흔들려요""…1천명 종로로 뛰어나온 공포의 4시간\n\r\n<YNA...","['""빌딩이 흔들려요""…', '옥상에 있는 냉각 타워 구조물이 부서졌다는 것입니다....",none
10255,AKR20220701167500004,2022-07-01T20:37:59,"""점심 장사 망쳐""…'흔들림 소동' 르메이에르빌딩 상인들 울상","""점심 장사 망쳐""…'흔들림 소동' 르메이에르빌딩 상인들 울상\n음식값 못 받고 저...","[""1일 건물이 흔들리는 사고로 1천여 명이 대피하는 소동이 벌어진 서울 종로구 르...",none
10212,AKR20220704050500004,2022-07-04T10:29:48,"'흔들림 소동' 르메이에르 빌딩, 6일 진동 계측 등 정밀검사","'흔들림 소동' 르메이에르 빌딩, 6일 진동 계측 등 정밀검사\n""진동 원인 99%...",['지난 1일 건물에 진동이 발생해 약 1천 명이 대피하는 소동이 벌어졌던 서울 종...,none
9334,AKR20220804139500004,2022-08-04T18:25:24,"美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""","美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""\n\r\n<YNAOBJECT ...","['빌딩 측은 이 차량을 몰던 운전자가 한국인 남성이며, 건물 앞에 주차하려다 단순...",none
9332,AKR20220804139551004,2022-08-04T20:18:11,"美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""(종합)","美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""(종합)\n\r\n<YNAOBJ...","['빌딩 측은 이 차량을 몰던 운전자가 한국인 남성이며, 건물 앞에 주차하려다 단순...",none
6783,AKR20220906055400530,2022-09-06T09:59:05,"[동정] 노동장관, 산업재해 노동자에게 위문품·영상메시지","[동정] 노동장관, 산업재해 노동자에게 위문품·영상메시지\n\r\n<YNAOBJEC...","['노동장관, 산업재해 노동자에게 위문품·영상메시지 이정식 고용노동부 장관은 추석 ...",none
3262,AKR20221102112000017,2022-11-02T16:11:37,"식약처 ""마약 관리 컨트롤타워 필요…마약안전기획관이 맡아야""","식약처 ""마약 관리 컨트롤타워 필요…마약안전기획관이 맡아야""\n임시마약류 지정기간도...",['식품의약품안전처는 2일 임시 조직으로 운영 중인 식품의약품안전처 마약안전기획관을...,식의약 안전 열린포럼
1895,PYH20221116222400013,2022-11-16T17:42:30,"현대차그룹, 산업안전상생재단 현판식 개최","현대차그룹, 산업안전상생재단 현판식 개최\r\n (서울=연합뉴스) 16일 서울...","['현대차그룹, 산업안전상생재단 현판식 개최 16일 서울 종로구 현대빌딩에서 열린 ...",none
1894,PYH20221116222500013,2022-11-16T17:42:44,"현대차그룹, 산업안전상생재단 현판식 개최","현대차그룹, 산업안전상생재단 현판식 개최\r\n (서울=연합뉴스) 16일 서울...","['현대차그룹, 산업안전상생재단 현판식 개최 16일 서울 종로구 현대빌딩에서 열린 ...",none
1252,PYH20221202157900013,2022-12-02T15:36:55,"CSMA·한국보건안전단체총연합회, 중대재해 제로 결의대회 개최","CSMA·한국보건안전단체총연합회, 중대재해 제로 결의대회 개최\r\n (서울=...","[""CSMA·한국보건안전단체총연합회, 중대재해 제로 결의대회 개최 이백훈 현대아산 ...",none
1251,PYH20221202158100013,2022-12-02T15:37:14,중대재해 제로 결의대회,중대재해 제로 결의대회\r\n (서울=연합뉴스) 2일 서울 종로구 현대그룹빌딩...,"[""중대재해 제로 결의대회 2일 서울 종로구 현대그룹빌딩에서 열린 '중대재해 제로(...",중대

In [301]:
# 날짜 꼭 바꾸걸아..

In [362]:
table = table[table['send_timestamp'] >= '2022-07-01'].sort_values('send_timestamp')
# table = table[table['send_timestamp'] < '2022-12-09'].sort_values('send_timestamp')
table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16 entries, 10303 to 1251
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   _id                        16 non-null     object
 1   send_timestamp             16 non-null     object
 2   YNewsML.NewsContent.Title  16 non-null     object
 3   YNewsML.NewsContent.Body   16 non-null     object
 4   Summarization              16 non-null     object
 5   key+jaccard                16 non-null     object
dtypes: object(6)
memory usage: 896.0+ bytes

In [341]:
# table[table['YNewsML.NewsContent.Title'].str.contains('종합.보')]

In [363]:
table

,_id,send_timestamp,YNewsML.NewsContent.Title,YNewsML.NewsContent.Body,Summarization,key+jaccard
10303,AKR20220701074500004,2022-07-01T11:26:40,종로 르메이에르 빌딩 흔들림 신고…원인 조사 중,종로 르메이에르 빌딩 흔들림 신고…원인 조사 중\n\r\n<YNAOBJECT id=...,['1일 오전 10시 25분께 서울 종로구 르메이에르 빌딩이 흔들렸다는 신고가 들어...,none
10295,AKR20220701074551004,2022-07-01T12:05:09,종로 르메이에르 빌딩 흔들림으로 대피…출입 막고 원인조사(종합),"종로 르메이에르 빌딩 흔들림으로 대피…출입 막고 원인조사(종합)\n""5분간 흔들림 ...",['1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 흔들렸다는 신고가 들어와 소방...,none
10274,AKR20220701074552004,2022-07-01T14:50:21,종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합2보),종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합2보)\n옥상 냉각타워 파손...,['1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파...,none
10269,AKR20220701074553004,2022-07-01T15:56:12,종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합3보),종로 르메이에르빌딩 5분간 흔들…1천여명 한때 대피(종합3보)\n옥상 냉각타워 파손...,['1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파...,none
10266,PYH20220701172200004,2022-07-01T16:35:00,종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피,종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피\r\n (서울=연합뉴스)...,['종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피 1일 오전 서울 종로구 르...,none
10262,AKR20220701140100704,2022-07-01T17:36:17,"[영상] ""빌딩이 흔들려요""…1천명 종로로 뛰어나온 공포의 4시간","[영상] ""빌딩이 흔들려요""…1천명 종로로 뛰어나온 공포의 4시간\n\r\n<YNA...","['""빌딩이 흔들려요""…', '옥상에 있는 냉각 타워 구조물이 부서졌다는 것입니다....",none
10255,AKR20220701167500004,2022-07-01T20:37:59,"""점심 장사 망쳐""…'흔들림 소동' 르메이에르빌딩 상인들 울상","""점심 장사 망쳐""…'흔들림 소동' 르메이에르빌딩 상인들 울상\n음식값 못 받고 저...","[""1일 건물이 흔들리는 사고로 1천여 명이 대피하는 소동이 벌어진 서울 종로구 르...",none
10212,AKR20220704050500004,2022-07-04T10:29:48,"'흔들림 소동' 르메이에르 빌딩, 6일 진동 계측 등 정밀검사","'흔들림 소동' 르메이에르 빌딩, 6일 진동 계측 등 정밀검사\n""진동 원인 99%...",['지난 1일 건물에 진동이 발생해 약 1천 명이 대피하는 소동이 벌어졌던 서울 종...,none
9334,AKR20220804139500004,2022-08-04T18:25:24,"美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""","美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""\n\r\n<YNAOBJECT ...","['빌딩 측은 이 차량을 몰던 운전자가 한국인 남성이며, 건물 앞에 주차하려다 단순...",none
9332,AKR20220804139551004,2022-08-04T20:18:11,"美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""(종합)","美대사관 차량 종로구 빌딩에 돌진…""주차하려다 실수""(종합)\n\r\n<YNAOBJ...","['빌딩 측은 이 차량을 몰던 운전자가 한국인 남성이며, 건물 앞에 주차하려다 단순...",none
6783,AKR20220906055400530,2022-09-06T09:59:05,"[동정] 노동장관, 산업재해 노동자에게 위문품·영상메시지","[동정] 노동장관, 산업재해 노동자에게 위문품·영상메시지\n\r\n<YNAOBJEC...","['노동장관, 산업재해 노동자에게 위문품·영상메시지 이정식 고용노동부 장관은 추석 ...",none
3262,AKR20221102112000017,2022-11-02T16:11:37,"식약처 ""마약 관리 컨트롤타워 필요…마약안전기획관이 맡아야""","식약처 ""마약 관리 컨트롤타워 필요…마약안전기획관이 맡아야""\n임시마약류 지정기간도...",['식품의약품안전처는 2일 임시 조직으로 운영 중인 식품의약품안전처 마약안전기획관을...,식의약 안전 열린포럼
1895,PYH20221116222400013,2022-11-16T17:42:30,"현대차그룹, 산업안전상생재단 현판식 개최","현대차그룹, 산업안전상생재단 현판식 개최\r\n (서울=연합뉴스) 16일 서울...","['현대차그룹, 산업안전상생재단 현판식 개최 16일 서울 종로구 현대빌딩에서 열린 ...",none
1894,PYH20221116222500013,2022-11-16T17:42:44,"현대차그룹, 산업안전상생재단 현판식 개최","현대차그룹, 산업안전상생재단 현판식 개최\r\n (서울=연합뉴스) 16일 서울...","['현대차그룹, 산업안전상생재단 현판식 개최 16일 서울 종로구 현대빌딩에서 열린 ...",none
1252,PYH20221202157900013,2022-12-02T15:36:55,"CSMA·한국보건안전단체총연합회, 중대재해 제로 결의대회 개최","CSMA·한국보건안전단체총연합회, 중대재해 제로 결의대회 개최\r\n (서울=...","[""CSMA·한국보건안전단체총연합회, 중대재해 제로 결의대회 개최 이백훈 현대아산 ...",none
1251,PYH20221202158100013,2022-12-02T15:37:14,중대재해 제로 결의대회,중대재해 제로 결의대회\r\n (서울=연합뉴스) 2일 서울 종로구 현대그룹빌딩...,"[""중대재해 제로 결의대회 2일 서울 종로구 현대그룹빌딩에서 열린 '중대재해 제로(...",중대

In [364]:
# 숫자바꿔주기..
table12 = table
table12.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16 entries, 10303 to 1251
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   _id                        16 non-null     object
 1   send_timestamp             16 non-null     object
 2   YNewsML.NewsContent.Title  16 non-null     object
 3   YNewsML.NewsContent.Body   16 non-null     object
 4   Summarization              16 non-null     object
 5   key+jaccard                16 non-null     object
dtypes: object(6)
memory usage: 896.0+ bytes

In [365]:
# df에서 table1제거 후 df 로 돌려줘..
table_li = table.index.tolist()
df = df[~df.index.isin(table_li)]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8350 entries, 0 to 11056
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   _id                        8350 non-null   object
 1   send_timestamp             8350 non-null   object
 2   YNewsML.NewsContent.Title  8350 non-null   object
 3   YNewsML.NewsContent.Body   8350 non-null   object
 4   Summarization              8350 non-null   object
 5   key+jaccard                8045 non-null   object
dtypes: object(6)
memory usage: 456.6+ KB

In [392]:
df_origin

,_id,send_timestamp,Title,Body,YNewsML.Metadata.Region.RegionCode,Summarization,NamedEntity,Keyword,img_link,issue_word,reason,class_code,class_name
0,AKR20221231041400061,2022-12-31T23:20:59,신분당선 판교∼정자역 사이서 전동차 멈춰1시간가량 불편,이영주 기자 = 31일 오후 9시 40분께 경기도 성남시 신분당선 판교역과 정자역 ...,"[{'code': 7005013, 'name': '성남'}, {'code': 700...",31일 오후 9시 40분께 경기도 성남시 신분당선 판교역과 정자역 사이 선로에서 전...,"[{'code': 'AF', 'word': '신분당선'}, {'code': 'LC'...","['정자역', '신분당선', '선로', '고장', '구원열차', '탑승', '꺼졌'...",img5.yna.co.kr/photo/cms/2016/05/02/01/C0A8CA3...,NaN,NaN,606010.0,철도사고
1,AKR20221231035000099,2022-12-31T18:08:13,남아공 가스트럭 폭발사고 사망자 34명으로 늘어,김성진 특파원 = 남아프리카공화국에서 지난 크리스마스이브에 발생한 가스 트럭 폭발 ...,NaN,"남아프리카공화국에서 지난 크리스마스이브에 발생한 가스 트럭 폭발 사고와 관련, 사망...","[{'code': 'LC', 'word': '남아공'}, {'code': 'AF',...","['남아공', '사망자', '폭발', '환자']",img8.yna.co.kr/photo/reuters/2022/12/29/PRU202...,NaN,NaN,606012.0,폭발사고
2,AKR20221231025151003,2022-12-31T16:16:20,"선로에 떨어진 부직포 때문에SRT, 운행 차질에 차량 고장까지",전날 선로 전기공급 차단 사고 여파이틀째 운행 취소 연기 잇따라 잇단 철도사고에 국...,NaN,선로 전기공급 차단 문제로 수서고속철도(SRT) 열차 운행이 이틀째 차질을 빚고 있...,"[{'code': 'AF', 'word': 'SRT'}, {'code': 'AF',...","['열차', '지연', 'GS건설', '고장', '전기공급', '차단', '통복터널']",img3.yna.co.kr/photo/yna/YH/2022/12/20/PYH2022...,NaN,NaN,606010.0,철도사고
3,AKR20221231025151003,2022-12-31T16:16:20,"선로에 떨어진 부직포 때문에SRT, 운행 차질에 차량 고장까지",전날 선로 전기공급 차단 사고 여파이틀째 운행 취소 연기 잇따라 잇단 철도사고에 국...,NaN,선로 전기공급 차단 문제로 수서고속철도(SRT) 열차 운행이 이틀째 차질을 빚고 있...,"[{'code': 'AF', 'word': 'SRT'}, {'code': 'AF',...","['열차', '지연', 'GS건설', '고장', '전기공급', '차단', '통복터널']",img3.yna.co.kr/photo/yna/YH/2022/12/20/PYH2022...,NaN,NaN,606001.0,사고일반
4,AKR20221231025100003,2022-12-31T12:57:34,선로 전기공급 끊기고 SRT 고장이틀째 대거 운행지연 취소,첫날 KTX SRT 최대 2시간여 운행지연열차 운행 축소 터널 하자보수 공사때 쓴 ...,NaN,선로 전기공급 차단 문제로 수서고속철도(SRT) 열차 운행이 이틀째 차질을 빚고 있...,"[{'code': 'AF', 'word': 'SRT'}, {'code': 'DT',...","['열차', '지연', 'SR', '전기공급', '끊기', '통복터널']",img4.yna.co.kr/photo/yna/YH/2022/12/20/PYH2022...,NaN,NaN,606010.0,철도사고
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14052,AKR20220607103300530,2022-06-08T10:00:07,"소방청 가스안전공사, 신에너지 사고 대응 업무협약",계승현 기자 = 소방청은 8일 한국가스안전공사와 수소 등 신에너지 관련 사고에 대응...,NaN,소방청은 8일 한국가스안전공사와 수소 등 신에너지 관련 사고에 대응하기 위해 업무협...,"[{'code': 'OG', 'word': '소방청가스안전공사'}, {'code':...","['한국가스안전공사', '사고수습', '수소경제', '기술교육', '소방청', '대...",img5.yna.co.kr/photo/cms/2019/04/16/62/PCM2019...,NaN,NaN,606008.0,안전관리
14053,PYH20220608015200017,2022-06-08T09:20:49,"LGU+, 서울지하철 8호선에 '스마트 역사' 구축",LG유플러스가 서울 지하철 8호선 18개 역사에 '스마트스테이션'을 구축하는 사업을...,NaN,"LGU+, 서울지하철 8호선에 '스마트 역사' 구축 LG유플러스가 서울 지하철 8호...","[{'code': 'OG', 'word': 'LGU+'}, {'code': 'AF'...","['lgu', '구축', '8호선', 'cctv', '스마트스테이션', '고도', ...",img4.yna.co.kr/photo/yna/YH/2022/06/07/PYH2022...,NaN,NaN,606008.0,안전관리
14054,AKR20220607168000017,2022-06-08T09:00:02,"LGU+, 서울지하철 8호선에 '스마트 역사' 구축 완료",역사 내 사고에 신속 대응해 역무 효율성 높여 임성호 기자 = LG유플러스는 서울 ...,NaN,LG유플러스는 서울 지하철 8호선 18개 역사에 '스마트스테이션'을 구축하는 사업을...,"[{'code': 'OG', 'word': 'LGU+'}, {'code': 'AF'...","['lg유플러스하이트', '서울교통공사', '역무원', '8호선', '스마트스테이션...",img9.yna.co.kr/etc/inner/KR/2022/06/07/AKR2022...,NaN,NaN,606008.0,안전관리
14055,AKR20220608017300530,2022-06-08T09:00:00,제조업 운반 하역 작업서 부상 가장 많이 발생전체 19.3%,김승욱 기자 = 3일 이상의 휴업이 필요한 부상 사고의 20% 가까이가 제조업 운반...,NaN,3일 이상의 휴업이 필요한 부상 사고의 20% 가까이가 제조업 운반·하역 작업에서 ...,"[{'code': 'DT', 'word': '3일 이상'}, {'code': 'QT...","['산업재해', '작업', '지방고용노동관서', '휴업', '3년간']",img7.yna.co.kr/photo/cms/2018/12/13/00/PCM2018...,NaN,NaN,606006.0,산재
14056,AKR20220608017300530,2022-06-08T09:00:00,제조업 운반 하역 작업서 부상 가장 많이 발생전체 19.3%,김승욱 기자 = 3일 이상의 휴업이 필요한 부상 사고의 20% 가까이가 제조업 운반...,NaN,3일 이상의 휴업이 필요한 부상 사고의 20% 가까이가 제조업 운반·하역 작업에서 ...,"[{'code': 'DT', 'word': '3일 이상'}, {'code': 'QT...","['산업재해', '작업', '지방고용노동관서', '휴업', '3년간']",img7.yna.co.kr/photo/cms/2018/12/13/00/PCM2018...,NaN,NaN,606008.0,안전관리

In [395]:
t_df1 = df_origin[df_origin['_id'].isin(table1['_id'].tolist())] 
t_df1['Issue'] = '이태원압사참사'
t_df2 = df_origin[df_origin['_id'].isin(table2['_id'].tolist())] 
t_df2['Issue'] = '제2경인 방음터널 화재'
t_df3 = df_origin[df_origin['_id'].isin(table3['_id'].tolist())] 
t_df3['Issue'] = '대전 현대아울렛 화재'
t_df4 = df_origin[df_origin['_id'].isin(table4['_id'].tolist())] 
t_df4['Issue'] = '지하철 3호선 화재'
t_df5 = df_origin[df_origin['_id'].isin(table5['_id'].tolist())] 
t_df5['Issue'] = '봉화 광산사고'
t_df6 = df_origin[df_origin['_id'].isin(table6['_id'].tolist())] 
t_df6['Issue'] = 'SPC 공장 사고'
t_df7 = df_origin[df_origin['_id'].isin(table7['_id'].tolist())] 
t_df7['Issue'] = '안성 추락사고'
t_df8 = df_origin[df_origin['_id'].isin(table8['_id'].tolist())] 
t_df8['Issue'] = '화일약품 공장 폭발'
t_df9 = df_origin[df_origin['_id'].isin(table9['_id'].tolist())] 
t_df9['Issue'] = '태풍 힌남노'
t_df11 = df_origin[df_origin['_id'].isin(table11['_id'].tolist())] 
t_df11['Issue'] = '이천 빌딩화재'
t_df12 = df_origin[df_origin['_id'].isin(table12['_id'].tolist())] 
t_df12['Issue'] = '종로 르메이에르 빌딩'

<ipython-input-395-1244e824bd71>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df1['Issue'] = '이태원압사참사'
<ipython-input-395-1244e824bd71>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df2['Issue'] = '제2경인 방음터널 화재'
<ipython-input-395-1244e824bd71>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df3['Issue'] = '대전 현대아울렛 화재'
<ipython-input-395-1244e824bd71>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df4['Issue'] = '지하철 3호선 화재'
<ipython-input-395-1244e824bd71>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df5['Issue'] = '봉화 광산사고'
<ipython-input-395-1244e824bd71>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df6['Issue'] = 'SPC 공장 사고'
<ipython-input-395-1244e824bd71>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df7['Issue'] = '안성 추락사고'
<ipython-input-395-1244e824bd71>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df8['Issue'] = '화일약품 공장 폭발'
<ipython-input-395-1244e824bd71>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df9['Issue'] = '태풍 힌남노'
<ipython-input-395-1244e824bd71>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df11['Issue'] = '이천 빌딩화재'
<ipython-input-395-1244e824bd71>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df12['Issue'] = '종로 르메이에르 빌딩'

In [398]:
total = pd.concat([t_df1,t_df2,t_df3,t_df4,t_df5,t_df6,t_df7,t_df8,t_df9,t_df11,t_df12])

In [405]:
df_origin = df_origin[~df_origin['_id'].isin(total['_id'].tolist())]

In [402]:
total

,_id,send_timestamp,Title,Body,YNewsML.Metadata.Region.RegionCode,Summarization,NamedEntity,Keyword,img_link,issue_word,reason,class_code,class_name,Issue
48,AKR20221230086300530,2022-12-30T15:10:24,"소방관 2만명 충원, 울진 삼척 산불소방청 10대 뉴스",김윤구 기자 = 올해 가장 많은 관심을 끈 소방청 뉴스로 '소방공무원 2만명 충원 ...,NaN,"올해 가장 많은 관심을 끈 소방청 뉴스로 '소방공무원 2만명 충원 완료', '울진·...","[{'code': 'CV', 'word': '소방관'}, {'code': 'QT',...","['소방공무원', '재난', '정책분야', '2만4천940HA', '대응체계', '...",img3.yna.co.kr/photo/yna/YH/2022/03/05/PYH2022...,힌남노태풍,NaN,606005.0,화재,이태원압사참사
49,AKR20221230086300530,2022-12-30T15:10:24,"소방관 2만명 충원, 울진 삼척 산불소방청 10대 뉴스",김윤구 기자 = 올해 가장 많은 관심을 끈 소방청 뉴스로 '소방공무원 2만명 충원 ...,NaN,"올해 가장 많은 관심을 끈 소방청 뉴스로 '소방공무원 2만명 충원 완료', '울진·...","[{'code': 'CV', 'word': '소방관'}, {'code': 'QT',...","['소방공무원', '재난', '정책분야', '2만4천940HA', '대응체계', '...",img3.yna.co.kr/photo/yna/YH/2022/03/05/PYH2022...,힌남노태풍,NaN,606008.0,안전관리,이태원압사참사
70,AKR20221230046200530,2022-12-30T10:20:10,주최자 없는 행사도 지자체가 안전관리인파관리시스템 구축,주요 재난상황 경찰청이 행안부와 시 도에 보고 지자체 재난상황실 상시 운영체계인력 ...,NaN,주요 재난상황에 대해 경찰청이 행정안전부와 시·도 등에 보고하도록 보고와 정보 공유...,"[{'code': 'OG', 'word': '경찰청'}, {'code': 'OG',...","['재난안전관리체계', '행안부', '인파관리시스템', '경찰', 'AI']",img1.yna.co.kr/photo/yna/YH/2022/12/30/PYH2022...,이태원압사참사,NaN,606008.0,안전관리,이태원압사참사
146,AKR20221229084600055,2022-12-29T12:53:46,슬픔이 전국에 있습니다 전주에 이태원 참사 시민분향소 설치,전북에 주거지 둔 유가족 주도로 설치내년 2월 5일까지 운영 나보배 기자 = 이태원...,"[{'code': 7009001, 'name': '전북'}, {'code': 700...",159명의 목숨을 앗아간 이태원 참사 희생자를 추모하는 분향소가 전북에도 차려졌다....,"[{'code': 'AF', 'word': '슬픔'}, {'code': 'LC', ...","['전북시민대책위원회', '추모', '시민분향소']",img8.yna.co.kr/etc/inner/KR/2022/12/29/AKR2022...,이태원압사참사,NaN,606008.0,안전관리,이태원압사참사
195,AKR20221228118100051,2022-12-28T16:55:02,이태원 참사 때 무용지물 재난통신망해맞이 행사 앞두고 훈련,16개 기관 참여인파 밀집사고 가정해 상황전파 현장대응 등 시연 손형주 기자 = 여...,NaN,상황을 전파받은 해운대구는 재난안전대책본부 가동하며 동시에 재난안전통신망을 활용해 ...,"[{'code': 'EV', 'word': '이태원 참사'}, {'code': 'Q...","['재난의료지원팀', '해운대해수욕장', '대응', '도착상황', '합동훈련', '...",img5.yna.co.kr/etc/inner/KR/2022/12/28/AKR2022...,세월호침몰사고,NaN,606001.0,사고일반,이태원압사참사
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13099,PYH20220701172200004,2022-07-01T16:35:00,종로 르메이에르빌딩 5분간 흔들1천여 명 한때 대피,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,NaN,종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피 1일 오전 서울 종로구 르메이...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['르메이에르빌딩', '종로타운', '흔들리', '냉각설비', '진동', '건물',...",img7.yna.co.kr/photo/yna/YH/2022/07/01/PYH2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩
13102,AKR20220701074553004,2022-07-01T15:56:12,종로 르메이에르빌딩 5분간 흔들1천여명 한때 대피,옥상 냉각타워 파손 영향날개 부러진 대형 팬이 회전하면서 균형 잃어 진동 4시간 가...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['건물안전진단', '진동', '부서지', '대피', '르메이에르빌딩']",img6.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩
13107,AKR20220701074552004,2022-07-01T14:50:21,종로 르메이에르빌딩 5분간 흔들1천여명 한때 대피,옥상 냉각타워 파손 영향날개 부러진 대형 팬이 회전하면서 균형 잃어 진동 4시간 가...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['건물안전진단', '진동', '대피', '부서지', '종로구']",img9.yna.co.kr/photo/yna/YH/2022/07/01/PYH2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩
13129,AKR20220701074551004,2022-07-01T12:05:09,종로 르메이에르 빌딩 흔들림으로 대피출입 막고 원인조사,5분간 흔들림 지속옥상 냉각팬 고장으로 생긴 불균형 추정 박규리 기자 = 1일 오전...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 흔들렸다는 신고가 들어와 소방당국...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['종로구청', '대피', '건물', '흔들렸', '소방관']",img6.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩
13138,AKR20220701074500004,2022-07-01T11:26:40,종로 르메이에르 빌딩 흔들림 신고원인 조사 중,박규리 기자 = 1일 오전 10시 25분께 서울 종로구 르메이에르 빌딩이 흔들렸다는...,NaN,1일 오전 10시 25분께 서울 종로구 르메이에르 빌딩이 흔들렸다는 신고가 들어와 ...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['종로구청', '소방당국', '흔들렸', '청진파출소', '불균형', '출동', ...",img0.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩

In [406]:
df_origin = pd.concat([df_origin,total])

In [407]:
df_origin.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14057 entries, 0 to 13138
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   _id                                 14057 non-null  object
 1   send_timestamp                      14057 non-null  object
 2   Title                               14034 non-null  object
 3   Body                                14057 non-null  object
 4   YNewsML.Metadata.Region.RegionCode  1847 non-null   object
 5   Summarization                       14057 non-null  object
 6   NamedEntity                         14057 non-null  object
 7   Keyword                             14057 non-null  object
 8   img_link                            13825 non-null  object
 9   issue_word                          4297 non-null   object
 10  reason                              410 non-null    object
 11  class_code                          13206 non-null  float64
 12  class_name                          13206 non-null  object
 13  Issue                               2198 non-null   object
dtypes: float64(1), object(13)
memory usage: 1.6+ MB

In [445]:
df_origin["Main_news_id"] = False
df_origin.columns

Index(['_id', 'send_timestamp', 'Title', 'Body',
       'YNewsML.Metadata.Region.RegionCode', 'Summarization', 'NamedEntity',
       'Keyword', 'img_link', 'issue_word', 'reason', 'class_code',
       'class_name', 'Issue', 'Main_news_id'],
      dtype='object')

In [434]:
df_origin.reset_index().drop(columns = ['index']) 
df_origin

,_id,send_timestamp,Title,Body,YNewsML.Metadata.Region.RegionCode,Summarization,NamedEntity,Keyword,img_link,issue_word,reason,class_code,class_name,Issue,Main_news_id
0,AKR20221231041400061,2022-12-31T23:20:59,신분당선 판교∼정자역 사이서 전동차 멈춰1시간가량 불편,이영주 기자 = 31일 오후 9시 40분께 경기도 성남시 신분당선 판교역과 정자역 ...,"[{'code': 7005013, 'name': '성남'}, {'code': 700...",31일 오후 9시 40분께 경기도 성남시 신분당선 판교역과 정자역 사이 선로에서 전...,"[{'code': 'AF', 'word': '신분당선'}, {'code': 'LC'...","['정자역', '신분당선', '선로', '고장', '구원열차', '탑승', '꺼졌'...",img5.yna.co.kr/photo/cms/2016/05/02/01/C0A8CA3...,NaN,NaN,606010.0,철도사고,NaN,
1,AKR20221231035000099,2022-12-31T18:08:13,남아공 가스트럭 폭발사고 사망자 34명으로 늘어,김성진 특파원 = 남아프리카공화국에서 지난 크리스마스이브에 발생한 가스 트럭 폭발 ...,NaN,"남아프리카공화국에서 지난 크리스마스이브에 발생한 가스 트럭 폭발 사고와 관련, 사망...","[{'code': 'LC', 'word': '남아공'}, {'code': 'AF',...","['남아공', '사망자', '폭발', '환자']",img8.yna.co.kr/photo/reuters/2022/12/29/PRU202...,NaN,NaN,606012.0,폭발사고,NaN,
10,AKR20221230074600052,2022-12-31T10:00:05,탈선 후 1년째 휴장애물단지 된 통영 욕지도 모노레일,최근 용역서 재시공 예산 100억 추산에 재운행 계획 원점 관광 활성화 vs 비용 ...,"[{'code': 7006001, 'name': '경남'}, {'code': 700...",지난해 11월 탈선 사고로 운행을 멈춘 경남 통영시 욕지도 모노레일이 1년 넘게 운...,"[{'code': 'DT', 'word': '1년째'}, {'code': 'LC',...","['통영관광개발공사', '모노레일', '탈선', '재운행', '고민', '2021년']",img2.yna.co.kr/etc/inner/KR/2022/12/30/AKR2022...,NaN,NaN,606010.0,철도사고,NaN,
11,AKR20221230074600052,2022-12-31T10:00:05,탈선 후 1년째 휴장애물단지 된 통영 욕지도 모노레일,최근 용역서 재시공 예산 100억 추산에 재운행 계획 원점 관광 활성화 vs 비용 ...,"[{'code': 7006001, 'name': '경남'}, {'code': 700...",지난해 11월 탈선 사고로 운행을 멈춘 경남 통영시 욕지도 모노레일이 1년 넘게 운...,"[{'code': 'DT', 'word': '1년째'}, {'code': 'LC',...","['통영관광개발공사', '모노레일', '탈선', '재운행', '고민', '2021년']",img2.yna.co.kr/etc/inner/KR/2022/12/30/AKR2022...,NaN,NaN,606008.0,안전관리,NaN,
12,AKR20221230139200004,2022-12-31T10:00:04,오세훈 안전에 모든 노력동행 매력도시 도약,윤보람 기자 = 오세훈 서울시장은 2023년 새해를 맞아 서울시민이 언제 어디를 가...,NaN,"오세훈 서울시장은 2023년 새해를 맞아 ""서울시민이 언제 어디를 가더라도 안전한 ...","[{'code': 'PS', 'word': '오세훈'}, {'code': 'CV',...","['서울시민', '2023년', '狡兎三窟']",img9.yna.co.kr/photo/yna/YH/2022/12/22/PYH2022...,이태원압사참사,NaN,606008.0,안전관리,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13099,PYH20220701172200004,2022-07-01T16:35:00,종로 르메이에르빌딩 5분간 흔들1천여 명 한때 대피,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,NaN,종로 르메이에르빌딩 5분간 흔들…1천여 명 한때 대피 1일 오전 서울 종로구 르메이...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['르메이에르빌딩', '종로타운', '흔들리', '냉각설비', '진동', '건물',...",img7.yna.co.kr/photo/yna/YH/2022/07/01/PYH2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩,
13102,AKR20220701074553004,2022-07-01T15:56:12,종로 르메이에르빌딩 5분간 흔들1천여명 한때 대피,옥상 냉각타워 파손 영향날개 부러진 대형 팬이 회전하면서 균형 잃어 진동 4시간 가...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['건물안전진단', '진동', '부서지', '대피', '르메이에르빌딩']",img6.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩,
13107,AKR20220701074552004,2022-07-01T14:50:21,종로 르메이에르빌딩 5분간 흔들1천여명 한때 대피,옥상 냉각타워 파손 영향날개 부러진 대형 팬이 회전하면서 균형 잃어 진동 4시간 가...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['건물안전진단', '진동', '대피', '부서지', '종로구']",img9.yna.co.kr/photo/yna/YH/2022/07/01/PYH2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩,
13129,AKR20220701074551004,2022-07-01T12:05:09,종로 르메이에르 빌딩 흔들림으로 대피출입 막고 원인조사,5분간 흔들림 지속옥상 냉각팬 고장으로 생긴 불균형 추정 박규리 기자 = 1일 오전...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 흔들렸다는 신고가 들어와 소방당국...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['종로구청', '대피', '건물', '흔들렸', '소방관']",img6.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩,
13138,AKR20220701074500004,2022-07-01T11:26:40,종로 르메이에르 빌딩 흔들림 신고원인 조사 중,박규리 기자 = 1일 오전 10시 25분께 서울 종로구 르메이에르 빌딩이 흔들렸다는...,NaN,1일 오전 10시 25분께 서울 종로구 르메이에르 빌딩이 흔들렸다는 신고가 들어와 ...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['종로구청', '소방당국', '흔들렸', '청진파출소', '불균형', '출동', ...",img0.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩,

In [449]:
df_origin.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14057 entries, 0 to 13138
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   _id                                 14057 non-null  object
 1   send_timestamp                      14057 non-null  object
 2   Title                               14034 non-null  object
 3   Body                                14057 non-null  object
 4   YNewsML.Metadata.Region.RegionCode  1847 non-null   object
 5   Summarization                       14057 non-null  object
 6   NamedEntity                         14057 non-null  object
 7   Keyword                             14057 non-null  object
 8   img_link                            13825 non-null  object
 9   issue_word                          4297 non-null   object
 10  reason                              410 non-null    object
 11  class_code                          13206 non-null  float64
 12  class_name                          13206 non-null  object
 13  Issue                               2198 non-null   object
 14  Main_news_id                        14057 non-null  bool
dtypes: bool(1), float64(1), object(13)
memory usage: 1.6+ MB

In [479]:
te = 'AKR20221029047958004'
df_origin[df_origin['_id']== te]['Main_news_id']

5205    False
Name: Main_news_id, dtype: bool

In [480]:
df_origin['Main_news_id'][5205] = True

<ipython-input-480-a926c4859eb1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_origin['Main_news_id'][5205] = True

In [481]:
df_origin['Main_news_id'].value_counts()

False    14041
True        16
Name: Main_news_id, dtype: int64

In [444]:
df_origin[df_origin['_id']== te]

,_id,send_timestamp,Title,Body,YNewsML.Metadata.Region.RegionCode,Summarization,NamedEntity,Keyword,img_link,issue_word,reason,class_code,class_name,Issue,Main_news_id
13102,AKR20220701074553004,2022-07-01T15:56:12,종로 르메이에르빌딩 5분간 흔들1천여명 한때 대피,옥상 냉각타워 파손 영향날개 부러진 대형 팬이 회전하면서 균형 잃어 진동 4시간 가...,NaN,1일 오전 서울 종로구 르메이에르 종로타운 빌딩이 건물 옥상 냉각설비 구조물 파손에...,"[{'code': 'LC', 'word': '종로'}, {'code': 'AF', ...","['건물안전진단', '진동', '부서지', '대피', '르메이에르빌딩']",img6.yna.co.kr/etc/inner/KR/2022/07/01/AKR2022...,NaN,NaN,606001.0,사고일반,종로 르메이에르 빌딩,

In [483]:
df_origin.to_csv('../Final_fire_news_6.csv', index=False, encoding='utf-8-sig')

/home/intern2/anaconda3/envs/intern/lib/python3.9/site-packages/pandas/core/internals/blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [484]:
df_origin.columns

Index(['_id', 'send_timestamp', 'Title', 'Body',
       'YNewsML.Metadata.Region.RegionCode', 'Summarization', 'NamedEntity',
       'Keyword', 'img_link', 'issue_word', 'reason', 'class_code',
       'class_name', 'Issue', 'Main_news_id'],
      dtype='object')

In [3]:
# df = pd.read_csv('../NEWS_NLP/Keword_cluster.csv'
qqq= pd.read_csv('../Final_fire_news_5.csv')
qqq.columns

Index(['_id', 'send_timestamp', 'Title', 'Body',
       'YNewsML.Metadata.Region.RegionCode',
       'YNewsML.Metadata.Region.RegionCode.code',
       'YNewsML.Metadata.Region.RegionCode.name', 'Summarization',
       'NamedEntity', 'Keyword', 'img_link', 'issue_word', 'reason',
       'class_code', 'class_name'],
      dtype='object')

In [19]:
qqq = qqq[['_id','Keyword']]
qqq_li = qqq.Keyword.tolist()
qqq_id = qqq['_id']

list_qqq = []
for i in qqq_li:
    # i = list_0[0]
    list_qqq.append(eval(i))
list_qqq
qqq.Keyword = list_qqq
qqq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14057 entries, 0 to 14056
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   _id      14057 non-null  object
 1   Keyword  14057 non-null  object
dtypes: object(2)
memory usage: 219.8+ KB

In [22]:
type(qqq.Keyword[0])

list

In [71]:
qqq = qqq.explode("Keyword", ignore_index=True)

In [72]:
qqq.to_csv('news_id_Keyword.csv', index=False, encoding='utf-8-sig')