In [19]:
import pandas as pd
import json
import requests
from urllib import parse
import xmltodict

In [20]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '112',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
dic
body = dic['response']['body']['items']['item']

dataframe = pd.json_normalize(body)
dataframe

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,112,인천,-7.8,None,None,None,1.9,None,...,None,1852,None,None,-8.7,None,-1.2,0.2,1.3,2.4
1,2021-01-01 02:00,2,112,인천,-7.8,None,None,None,1.0,None,...,None,1745,None,None,-9.0,None,-1.3,0.1,1.3,2.2
2,2021-01-01 03:00,3,112,인천,-8.0,None,None,None,1.9,None,...,None,1950,None,None,-9.0,None,-1.4,0.1,1.2,2.2
3,2021-01-01 04:00,4,112,인천,-7.9,None,None,None,1.9,None,...,None,1937,None,None,-9.0,None,-1.5,0.0,1.2,2.2
4,2021-01-01 05:00,5,112,인천,-7.9,None,None,None,3.1,None,...,14,1736,None,None,-8.6,None,-1.6,0.0,1.2,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,2021-02-11 11:00,995,112,인천,5.8,None,None,None,1.8,None,...,None,340,None,40,8.9,None,3.0,2.0,2.2,2.7
995,2021-02-11 12:00,996,112,인천,7.3,None,None,None,1.3,None,...,None,394,None,40,12.4,None,4.1,2.4,2.3,2.6
996,2021-02-11 13:00,997,112,인천,8.2,None,None,None,1.4,None,...,None,410,None,40,15.7,None,5.3,3.0,2.4,2.7
997,2021-02-11 14:00,998,112,인천,8.3,None,None,None,3.7,None,...,None,455,None,40,13.7,None,6.3,3.6,2.7,2.7
998,2021-02-11 15:00,999,112,인천,8.6,None,None,None,2.0,None,...,None,394,None,40,12.2,None,6.6,4.0,3.0,2.8

In [21]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '112',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '112',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df = pd.concat([df, dataframe])
df

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,112,인천,-7.8,None,None,None,1.9,None,...,None,1852,None,None,-8.7,None,-1.2,0.2,1.3,2.4
1,2021-01-01 02:00,2,112,인천,-7.8,None,None,None,1.0,None,...,None,1745,None,None,-9.0,None,-1.3,0.1,1.3,2.2
2,2021-01-01 03:00,3,112,인천,-8.0,None,None,None,1.9,None,...,None,1950,None,None,-9.0,None,-1.4,0.1,1.2,2.2
3,2021-01-01 04:00,4,112,인천,-7.9,None,None,None,1.9,None,...,None,1937,None,None,-9.0,None,-1.5,0.0,1.2,2.2
4,2021-01-01 05:00,5,112,인천,-7.9,None,None,None,3.1,None,...,14,1736,None,None,-8.6,None,-1.6,0.0,1.2,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,112,인천,-0.4,None,None,None,1.3,None,...,None,3068,None,None,-0.4,None,0.6,0.9,1.8,2.9
270,2022-12-20 22:00,17254,112,인천,-0.4,None,None,None,2.8,None,...,None,3132,None,None,-0.5,None,0.6,0.9,1.8,2.9
271,2022-12-20 23:00,17255,112,인천,-0.3,None,None,None,3.3,None,...,None,3699,None,None,-0.5,None,0.5,0.9,1.8,2.9
272,2022-12-21 00:00,17256,112,인천,-0.1,None,None,None,4.9,None,...,37,3447,None,None,-0.5,None,0.5,0.9,1.8,2.9
273,2022-12-21 01:00,17257,112,인천,0.2,None,None,None,5.1,None,...,16,3619,None,None,-0.5,None,0.6,0.9,1.8,2.9

In [22]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '203',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df1 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '203',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df1 = pd.concat([df1, dataframe])
df1

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,203,이천,-10.3,None,None,None,1.0,None,...,None,1331,None,None,-5.6,None,None,None,None,None
1,2021-01-01 02:00,2,203,이천,-11.1,None,None,None,0.5,None,...,None,1569,None,None,-5.9,None,None,None,None,None
2,2021-01-01 03:00,3,203,이천,-10.5,None,None,None,0.7,None,...,None,1366,None,None,-6.1,None,None,None,None,None
3,2021-01-01 04:00,4,203,이천,-11.7,None,None,None,0.2,None,...,None,1254,None,None,-6.4,None,None,None,None,None
4,2021-01-01 05:00,5,203,이천,-12.3,None,None,None,0.8,None,...,None,881,None,None,-6.6,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,203,이천,-3.7,None,None,None,0.5,None,...,None,1749,None,None,-0.3,None,None,None,None,None
270,2022-12-20 22:00,17254,203,이천,-3.8,None,None,None,0.1,None,...,None,1637,None,None,-0.3,None,None,None,None,None
271,2022-12-20 23:00,17255,203,이천,-4.3,None,None,None,0.2,None,...,None,1264,None,None,-0.3,None,None,None,None,None
272,2022-12-21 00:00,17256,203,이천,-3.7,None,None,None,0.1,None,...,None,1702,None,None,-0.3,None,None,None,None,None
273,2022-12-21 01:00,17257,203,이천,-4.1,None,None,None,0.6,None,...,None,1549,None,None,-0.3,None,None,None,None,None

In [23]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '202',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df2 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '202',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df2 = pd.concat([df2, dataframe])
df2

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,202,양평,-10.3,None,None,None,0.6,None,...,None,1586,None,None,-11.3,None,None,None,None,None
1,2021-01-01 02:00,2,202,양평,-10.8,None,None,None,0.3,None,...,None,1286,None,None,-11.4,None,None,None,None,None
2,2021-01-01 03:00,3,202,양평,-10.6,None,None,None,0.3,None,...,None,1086,None,None,-11.5,None,None,None,None,None
3,2021-01-01 04:00,4,202,양평,-11.7,None,None,None,0.5,None,...,None,1401,None,None,-11.8,None,None,None,None,None
4,2021-01-01 05:00,5,202,양평,-12.0,None,None,None,0.7,None,...,None,1474,None,None,-12.0,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,202,양평,-2.7,None,None,None,0.9,None,...,None,1732,None,None,-0.7,None,None,None,None,None
270,2022-12-20 22:00,17254,202,양평,-2.6,None,None,None,1.8,None,...,None,1659,None,None,-0.7,None,None,None,None,None
271,2022-12-20 23:00,17255,202,양평,-2.8,None,None,None,0.5,None,...,None,1590,None,None,-0.8,None,None,None,None,None
272,2022-12-21 00:00,17256,202,양평,-2.8,None,None,None,0.9,None,...,None,1560,None,None,-0.7,None,None,None,None,None
273,2022-12-21 01:00,17257,202,양평,-2.9,None,None,None,0.3,None,...,None,1519,None,None,-0.7,None,None,None,None,None

In [24]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '119',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df3 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '119',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df3 = pd.concat([df3, dataframe])
df3

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,119,수원,-8.6,None,None,None,0.9,None,...,None,1939,None,None,-6.4,None,None,None,None,None
1,2021-01-01 02:00,2,119,수원,-9.8,None,None,None,1.4,None,...,None,1822,None,None,-6.7,None,None,None,None,None
2,2021-01-01 03:00,3,119,수원,-9.8,None,None,None,1.0,None,...,None,1932,None,None,-7.0,None,None,None,None,None
3,2021-01-01 04:00,4,119,수원,-9.8,None,None,None,1.5,None,...,None,1854,None,None,-7.2,None,None,None,None,None
4,2021-01-01 05:00,5,119,수원,-9.2,None,None,None,1.6,None,...,None,1848,None,None,-7.2,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,119,수원,-1.3,None,None,None,2.5,None,...,40,2000,None,None,-0.5,None,None,None,None,None
270,2022-12-20 22:00,17254,119,수원,-1.6,None,None,None,2.4,None,...,52,1998,None,None,-0.5,None,None,None,None,None
271,2022-12-20 23:00,17255,119,수원,-1.5,None,None,None,2.2,None,...,41,1980,None,None,-0.6,None,None,None,None,None
272,2022-12-21 00:00,17256,119,수원,-1.7,None,None,None,1.9,None,...,35,2043,None,None,-0.6,None,None,None,None,None
273,2022-12-21 01:00,17257,119,수원,-1.5,None,None,None,2.7,None,...,38,1950,None,None,-0.6,None,None,None,None,None

In [25]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '108',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df4 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '108',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df4 = pd.concat([df4, dataframe])
df4

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,108,서울,-8.7,None,None,None,2.4,None,...,None,2000,None,None,-6.9,None,-1.0,-0.8,0.3,1.6
1,2021-01-01 02:00,2,108,서울,-9.1,None,None,None,1.6,None,...,None,2000,None,None,-7.1,None,-1.1,-0.8,0.3,1.6
2,2021-01-01 03:00,3,108,서울,-9.3,None,None,None,1.1,None,...,None,2000,None,None,-7.3,None,-1.2,-0.9,0.3,1.6
3,2021-01-01 04:00,4,108,서울,-9.3,None,None,None,0.3,None,...,None,2000,None,None,-7.5,None,-1.3,-1.0,0.2,1.5
4,2021-01-01 05:00,5,108,서울,-9.7,None,None,None,1.9,None,...,None,2000,None,None,-7.6,None,-1.3,-1.0,0.2,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,108,서울,-0.6,None,None,None,3.4,None,...,28,2000,None,None,-0.6,None,0.0,-0.3,0.2,1.7
270,2022-12-20 22:00,17254,108,서울,-0.7,None,None,None,3.5,None,...,32,2000,None,None,-0.8,None,0.0,-0.3,0.2,1.7
271,2022-12-20 23:00,17255,108,서울,-0.8,None,None,None,3.5,None,...,36,2000,None,None,-1.0,None,0.0,-0.3,0.2,1.7
272,2022-12-21 00:00,17256,108,서울,-0.6,None,None,None,2.7,None,...,11,2000,None,None,-1.0,None,-0.1,-0.3,0.2,1.7
273,2022-12-21 01:00,17257,108,서울,-0.7,None,None,None,3.1,None,...,30,2000,None,None,-1.3,None,0.0,-0.3,0.2,1.7

In [26]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '98',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df5 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '98',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df5 = pd.concat([df5, dataframe])
df5

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,98,동두천,-11.2,None,None,None,0.5,None,...,None,4873,None,None,-10.5,None,None,None,None,None
1,2021-01-01 02:00,2,98,동두천,-11.6,None,None,None,0.3,None,...,None,4269,None,None,-10.9,None,None,None,None,None
2,2021-01-01 03:00,3,98,동두천,-12.0,None,None,None,0.5,None,...,None,4435,None,None,-11.2,None,None,None,None,None
3,2021-01-01 04:00,4,98,동두천,-12.5,None,None,None,0.7,None,...,None,5000,None,None,-11.4,None,None,None,None,None
4,2021-01-01 05:00,5,98,동두천,-12.5,None,None,None,0.9,None,...,None,4928,None,None,-11.5,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,98,동두천,-1.5,None,None,None,1.7,None,...,None,2300,None,None,-0.9,None,None,None,None,None
270,2022-12-20 22:00,17254,98,동두천,-1.8,None,None,None,0.0,None,...,None,2279,None,None,-1.0,None,None,None,None,None
271,2022-12-20 23:00,17255,98,동두천,-2.1,None,None,None,0.0,None,...,None,2302,None,None,-1.3,None,None,None,None,None
272,2022-12-21 00:00,17256,98,동두천,-1.9,None,None,None,1.1,None,...,None,2167,None,None,-1.3,None,None,None,None,None
273,2022-12-21 01:00,17257,98,동두천,-1.5,None,None,None,0.8,None,...,None,2626,None,None,-1.5,None,None,None,None,None

In [27]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '99',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df6 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '99',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df6 = pd.concat([df6, dataframe])
df6

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,99,파주,-12.7,None,None,None,1.1,None,...,None,2034,None,None,-10.4,None,None,None,None,None
1,2021-01-01 02:00,2,99,파주,-12.4,None,None,None,0.2,None,...,None,1933,None,None,-10.7,None,None,None,None,None
2,2021-01-01 03:00,3,99,파주,-13.1,None,None,None,1.0,None,...,None,2050,None,None,-11.0,None,None,None,None,None
3,2021-01-01 04:00,4,99,파주,-13.7,None,None,None,0.5,None,...,None,1892,None,None,-11.4,None,None,None,None,None
4,2021-01-01 05:00,5,99,파주,-13.7,None,None,None,0.2,None,...,None,1921,None,None,-10.9,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,99,파주,-2.1,None,None,None,1.6,None,...,None,3790,None,None,-0.7,None,None,None,None,None
270,2022-12-20 22:00,17254,99,파주,-2.3,None,None,None,1.3,None,...,None,3752,None,None,-0.9,None,None,None,None,None
271,2022-12-20 23:00,17255,99,파주,-2.3,None,None,None,0.1,None,...,None,3446,None,None,-0.9,None,None,None,None,None
272,2022-12-21 00:00,17256,99,파주,-2.5,None,None,None,0.9,None,...,None,3248,None,None,-1.0,None,None,None,None,None
273,2022-12-21 01:00,17257,99,파주,-2.8,None,None,None,0.6,None,...,None,2952,None,None,-1.3,None,None,None,None,None

In [28]:
url = 'http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList'
key = 'buNPq8BZdGw2p%2B3l2B7IMBy3e9PX5fahBKLPiW518y4yMZsQFDJeQW9fpNMb2nt7Xu6j4vz6txHwT5%2BrcFrwhA%3D%3D'

queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
parse.quote_plus("dataCd"): 'ASOS',
parse.quote_plus("dateCd"): 'HR',
parse.quote_plus("startDt"): '20210101',
parse.quote_plus("startHh"): '01',
parse.quote_plus("endDt"): '20221221',
parse.quote_plus("endHh"): '01',
parse.quote_plus("stnIds"): '102',
parse.quote_plus("pageNo"): 1,
parse.quote_plus("numOfRows"): 999,
})

# xml로 받아온 response
response = requests.get(url + queryParams).text
# xmltodict로 dictionary형태로 바꿔줌
jsonString = json.dumps(xmltodict.parse(response), indent=4)
# dictiondary to json
dic = json.loads(jsonString)
#dic
body = dic['response']['body']['items']['item']

df7 = pd.json_normalize(body)

for i in range(2, 19):
    queryParams = f'?{parse.quote_plus("serviceKey")}={key}&' + parse.urlencode({
    parse.quote_plus("dataCd"): 'ASOS',
    parse.quote_plus("dateCd"): 'HR',
    parse.quote_plus("startDt"): '20210101',
    parse.quote_plus("startHh"): '01',
    parse.quote_plus("endDt"): '20221221',
    parse.quote_plus("endHh"): '01',
    parse.quote_plus("stnIds"): '102',
    parse.quote_plus("pageNo"): i,
    parse.quote_plus("numOfRows"): 999,
    })

    # xml로 받아온 response
    response = requests.get(url + queryParams).text
    # xmltodict로 dictionary형태로 바꿔줌
    jsonString = json.dumps(xmltodict.parse(response), indent=4)
    # dictiondary to json
    dic = json.loads(jsonString)
    #dic
    body = dic['response']['body']['items']['item']

    dataframe = pd.json_normalize(body)
    df7 = pd.concat([df7, dataframe])
df7

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,102,백령도,-0.9,None,None,None,4.5,None,...,13,4361,None,None,-0.5,None,None,None,None,None
1,2021-01-01 02:00,2,102,백령도,-2.4,None,None,9,3.8,None,...,2,450,None,05,-0.5,None,None,None,None,None
2,2021-01-01 03:00,3,102,백령도,-1.9,None,0.6,None,2.3,None,...,2,2694,None,05,-0.5,None,None,None,None,None
3,2021-01-01 04:00,4,102,백령도,-2.7,None,None,9,0.0,None,...,3,2418,None,05,-0.4,None,None,None,None,None
4,2021-01-01 05:00,5,102,백령도,-2.3,None,None,9,2.1,None,...,12,2694,None,05,-0.4,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,102,백령도,2.4,None,0.1,None,7.0,None,...,4,1651,None,1006,-0.2,None,None,None,None,None
270,2022-12-20 22:00,17254,102,백령도,3.4,None,None,9,9.7,None,...,5,1709,None,0601,0.0,None,None,None,None,None
271,2022-12-20 23:00,17255,102,백령도,3.8,None,None,9,7.3,None,...,4,849,None,1901,-0.2,None,None,None,None,None
272,2022-12-21 00:00,17256,102,백령도,3.4,None,6.2,None,6.6,None,...,4,408,None,1901,1.3,None,None,None,None,None
273,2022-12-21 01:00,17257,102,백령도,5.1,None,None,9,2.5,None,...,3,1568,None,1901,1.7,None,None,None,None,None

In [29]:
main_df = pd.concat([df, df1, df2, df3, df4, df5, df6, df7])
main_df

,tm,rnum,stnId,stnNm,ta,taQcflg,rn,rnQcflg,ws,wsQcflg,...,lcsCh,vs,gndSttCd,dmstMtphNo,ts,tsQcflg,m005Te,m01Te,m02Te,m03Te
0,2021-01-01 01:00,1,112,인천,-7.8,None,None,None,1.9,None,...,None,1852,None,None,-8.7,None,-1.2,0.2,1.3,2.4
1,2021-01-01 02:00,2,112,인천,-7.8,None,None,None,1.0,None,...,None,1745,None,None,-9.0,None,-1.3,0.1,1.3,2.2
2,2021-01-01 03:00,3,112,인천,-8.0,None,None,None,1.9,None,...,None,1950,None,None,-9.0,None,-1.4,0.1,1.2,2.2
3,2021-01-01 04:00,4,112,인천,-7.9,None,None,None,1.9,None,...,None,1937,None,None,-9.0,None,-1.5,0.0,1.2,2.2
4,2021-01-01 05:00,5,112,인천,-7.9,None,None,None,3.1,None,...,14,1736,None,None,-8.6,None,-1.6,0.0,1.2,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,2022-12-20 21:00,17253,102,백령도,2.4,None,0.1,None,7.0,None,...,4,1651,None,1006,-0.2,None,None,None,None,None
270,2022-12-20 22:00,17254,102,백령도,3.4,None,None,9,9.7,None,...,5,1709,None,0601,0.0,None,None,None,None,None
271,2022-12-20 23:00,17255,102,백령도,3.8,None,None,9,7.3,None,...,4,849,None,1901,-0.2,None,None,None,None,None
272,2022-12-21 00:00,17256,102,백령도,3.4,None,6.2,None,6.6,None,...,4,408,None,1901,1.3,None,None,None,None,None
273,2022-12-21 01:00,17257,102,백령도,5.1,None,None,9,2.5,None,...,3,1568,None,1901,1.7,None,None,None,None,None

In [30]:
main_df.to_csv('기상.csv', encoding = 'utf-8-sig')